# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'satellite_Qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(588, 509)
        self.fileBtn = QtWidgets.QPushButton(Form)
        self.fileBtn.setGeometry(QtCore.QRect(30, 360, 271, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.fileBtn.setFont(font)
        self.fileBtn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.fileBtn.setTabletTracking(False)
        self.fileBtn.setStyleSheet("QPushButton\n"
"{\n"
"    color: #1296db;\n"
"    background-color:transparent;\n"
"    font: 75 20pt \"微软雅黑\";\n"
"    border-style:outset;\n"
"    border-width:2px;\n"
"    border-color:#0055ff; \n"
"    border-radius:10px; \n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:rgb(97 , 179 , 246);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    color:rgb(0 , 109 , 176);\n"
"}\n"
"")
        self.fileBtn.setIconSize(QtCore.QSize(44, 28))
        self.fileBtn.setDefault(True)
        self.fileBtn.setObjectName("fileBtn")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 541, 321))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox\n"
"{\n"
"    color: #1296db;\n"
"    background-color:transparent;\n"
"    border-style:outset;\n"
"    border-width:2px;\n"
"    border-color:#0055ff; \n"
"    border-radius:10px; \n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.pre_imag_info = QtWidgets.QLabel(self.groupBox)
        self.pre_imag_info.setGeometry(QtCore.QRect(90, 20, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pre_imag_info.setFont(font)
        self.pre_imag_info.setObjectName("pre_imag_info")
        self.Infolabel = QtWidgets.QLabel(self.groupBox)
        self.Infolabel.setGeometry(QtCore.QRect(30, 280, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Infolabel.setFont(font)
        self.Infolabel.setObjectName("Infolabel")
        self.result_label = QtWidgets.QLabel(self.groupBox)
        self.result_label.setGeometry(QtCore.QRect(320, 130, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Bradley Hand")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.result_label.setFont(font)
        self.result_label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.result_label.setStyleSheet("QLabel\n"
"{\n"
"    color: #1296db;\n"
"    background-color:transparent;\n"
"    border-style:outset;\n"
"    border-width:2px;\n"
"    border-color:#0055ff; \n"
"    border-radius:10px; \n"
"}")
        self.result_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.result_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.result_label.setTextFormat(QtCore.Qt.MarkdownText)
        self.result_label.setObjectName("result_label")
        self.pre_imag_label = QtWidgets.QLabel(self.groupBox)
        self.pre_imag_label.setGeometry(QtCore.QRect(30, 50, 281, 221))
        self.pre_imag_label.setStyleSheet("QLabel\n"
"{\n"
"    color: #1296db;\n"
"    background-color:transparent;\n"
"    \n"
"    border-style:outset;\n"
"    border-width:3px;\n"
"    border-color:#0055ff; \n"
"    border-radius:10px; \n"
"}")
        self.pre_imag_label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.pre_imag_label.setText("")
        self.pre_imag_label.setPixmap(QtGui.QPixmap(":/satellite_image/WechatIMG105.png"))
        self.pre_imag_label.setScaledContents(True)
        self.pre_imag_label.setObjectName("pre_imag_label")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(330, 90, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pre_imag_info.raise_()
        self.Infolabel.raise_()
        self.result_label.raise_()
        self.label_3.raise_()
        self.pre_imag_label.raise_()
        self.check_Button = QtWidgets.QPushButton(Form)
        self.check_Button.setGeometry(QtCore.QRect(340, 350, 201, 91))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(12)
        self.check_Button.setFont(font)
        self.check_Button.setStyleSheet("QPushButton\n"
"{\n"
"    color: #1296db;\n"
"    background-color:transparent;\n"
"    font: 100 26pt \"微软雅黑\";\n"
"    border-style:outset;\n"
"    border-width:3px;\n"
"    border-color:#0055ff; \n"
"    border-radius:10px; \n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:rgb(97 , 179 , 246);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    color:rgb(0 , 109 , 176);\n"
"}\n"
"\n"
"")
        self.check_Button.setObjectName("check_Button")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(239, 5, 131, 41))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/bg_image/1131665048665_.pic.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-120, -40, 821, 561))
        self.label.setStyleSheet("image: url(:/satellite_image/1131665048665.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/bg_image/1131665048665_.pic.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.img_file_btn = QtWidgets.QPushButton(Form)
        self.img_file_btn.setGeometry(QtCore.QRect(30, 410, 271, 31))
        self.img_file_btn.setStyleSheet("QPushButton\n"
"{\n"
"    color: #1296db;\n"
"    background-color:transparent;\n"
"    font: 75 20pt \"微软雅黑\";\n"
"    border-style:outset;\n"
"    border-width:2px;\n"
"    border-color:#0055ff; \n"
"    border-radius:10px; \n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:rgb(97 , 179 , 246);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    color:rgb(0 , 109 , 176);\n"
"}\n"
"")
        self.img_file_btn.setObjectName("img_file_btn")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(90, 460, 401, 31))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"     border-radius: 5px; \n"
"    background-color:transparent;\n"
"    text-align: center;\n"
"    border-style:outset;\n"
"    border-width:2px;\n"
"    border-color:#0055ff; \n"
"    border-radius:10px; \n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label.raise_()
        self.fileBtn.raise_()
        self.groupBox.raise_()
        self.check_Button.raise_()
        self.label_2.raise_()
        self.img_file_btn.raise_()
        self.progressBar.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Satellite Images Prediction"))
        self.fileBtn.setText(_translate("Form", "🛰️Input a satellite imge here"))
        # self.groupBox.setTitle(_translate("Form", "@ Victor Lee"))
        self.pre_imag_info.setText(_translate("Form", "<html><head/><body><p>🛰️<span style=\" color:#ffffff;\">satellite image </span>👇</p></body></html>"))
        self.Infolabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; color:#ff2600;\">⚠️❗️waiting for loading image❗️</span></p></body></html>"))
        self.result_label.setText(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">👇recognized result</span></p></body></html>"))
        self.check_Button.setText(_translate("Form", "🚀start check!"))
        self.img_file_btn.setText(_translate("Form", "📁Input a satellite fille here"))
import pic
